### ISSUE TITLE
Error: 8811 not defined

### ISSUE THREAD

**Issue by rcnlee** [timholy/IProfile.jl#29]
Hello,

I followed the instructions on the main page, i.e.,

using IProfile
@iprofile begin
#my function goes here
end

(This is inside a module)

and I am receiving the following error when I run: @iprofile report
Error: 8811 not defined

It only happens on some functions--the ones in this module, for example.  Some other modules seem to be OK.
Any ideas what this may be?

I'm running Windows 8 with Julia 0.3.3

Thanks!

Ritchie

**Comment by timholy** [comment]
I'm not sure this works inside modules. Is there any reason not to use the profiler in base? http://docs.julialang.org/en/release-0.3/manual/profile/

**Comment by rcnlee** [comment]
Hi Tim,

I'm not seeing many lines referencing my code in Profile.print(), most of them are in inference.jl or reflection.jl.  The other problem is that ProfileView is crashing with a Tk error.  (Actually it looks like you just replied to that issue.)

I'm also very interested in the breakdown of memory allocation.

Ritchie

**Comment by timholy** [comment]
You have to run your code twice: once to get everything to compile, and then use `@profile ...` to profile it. That way you don't end up profiling compilation itself.

**Comment by timholy** [comment]
Also, if you want detailed info on memory allocation: http://docs.julialang.org/en/release-0.3/manual/profile/#memory-allocation-analysis

**Comment by rcnlee** [comment]
I see! Thanks for the pointer!
